### Local Makefile, adding the exercise-specific code modules.  ###
### Anything else is defined in the upper directory centralized ###
### Makefile config.mk                                          ###
### ----------------------------------------------------------- ###
include ../config.mk
ADD_SRC += src/tm1640.v src/ctl_7seg9.v src/hexdigit.v
PIN_DEF = src/gm-proto.ccf
TOP = pmod_7seg9_2
