### Local Makefile, adding the exercise-specific code modules.  ###
### Anything else is defined in the upper directory centralized ###
### Makefile config.mk (must be last on the bottom of this file)###
### ----------------------------------------------------------- ###
ADD_SRC += src/tm1640.v src/ctl_7seg9.v src/hexdigit.v src/debounce.v
PIN_DEF = src/gm.ccf
TOP = pmod_7seg9_2
include ../config.mk
