name: rpi-test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Add libs
      run: sudo apt-get install -y libgpiod-dev
    - name: make all
      run: |
        cd ./examples/pi-tm1640
        make all
